version: "3.7"
services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: qo19NJfonsbc
  biubiubiu:
    image: ufo22940268/biubiubiu
    container_name: biu
    ports:
      - "3000:3000"
