name: ci
on:
  push:
    branches: master

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Build and push base
        id: docker_build_base
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./base.Dockerfile
          push: false
          tags: ufo22940268/biubiubiu-base:latest
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ufo22940268/biubiubiu:latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
      - name: Deploy
        uses: appleboy/jenkins-action@master
        with:
          url: "https://jenkins.biubiubiu.biz"
          user: "cc"
          token: ${{ secrets.JENKINS_TOKEN }}
          job: "Update biubiubiu"
